game.version=Roguera build v0.4.0_alpha:1111:1353
dungeon.world.size.xbound=200
dungeon.world.size.ybound=100
dungeon.world.rooms.count=5
window.size.width=100
window.size.height=30
#window.title
font.size=16
font.filepath=src/main/resources/PixelCode.ttf