game.version=Roguera build v0.4.0_alpha:1111:1353
game.random.seed=
dungeon.world.size.xbound=200
dungeon.world.size.ybound=100
dungeon.world.rooms.count=5
window.size.width=105
window.size.height=30
font.size=18
font.filepath=/PixelCode.ttf

# debug settings
debug.show.system-info=true
debug.show.draw-room=false
debug.show.dungeon-generate=false
debug.show.key-input=false
debug.show.player-movement=false
debug.show.event-raise=false
debug.show.room-create=false
debug.dump.events=true
debug.dump.objects=true